services:
  _defaults:
    public: true

  Psgdpr:
    class: "Psgdpr"
    factory: ["Module", "getInstanceByName"]
    arguments:
      - "psgdpr"

  Presta_Shop\Module\Psgdpr\Repository\Logger_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Logger_Repository'
    arguments:
      - "@Doctrine\\Persistence\\ManagerRegistry"

  Presta_Shop\Module\Psgdpr\Repository\Customer_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Customer_Repository'
    arguments:
      - "@doctrine.dbal.default_connection"

  Presta_Shop\Module\Psgdpr\Service\Logger_Service:
    class: 'Presta_Shop\Module\Psgdpr\Service\Logger_Service'
    arguments:
      - "@PrestaShop\\Module\\Psgdpr\\Repository\\LoggerRepository"
      - "@PrestaShop\\Module\\Psgdpr\\Repository\\CustomerRepository"

  Presta_Shop\Module\Psgdpr\Service\Export_Service:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export_Service'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@=service("Psgdpr").getTranslator()'

  Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory'
    arguments:
      - !tagged_iterator psgdpr.export.customerData

  Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Csv:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Csv'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'

  Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Pdf:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Pdf'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'

  Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Json:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Json'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'

  Presta_Shop\Module\Psgdpr\Service\Front_Responder\Front_Responder_Factory:
    class: 'Presta_Shop\Module\Psgdpr\Service\Front_Responder\Front_Responder_Factory'
    arguments:
      - !tagged_iterator psgdpr.frontResponder

  Presta_Shop\Module\Psgdpr\Service\Front_Responder\Strategy\Front_Responder_For_Csv:
    class: 'Presta_Shop\Module\Psgdpr\Service\Front_Responder\Strategy\Front_Responder_For_Csv'
    tags: ["psgdpr.frontResponder"]
    arguments:
      - '@Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Export_Service'

  Presta_Shop\Module\Psgdpr\Service\Front_Responder\Strategy\Front_Responder_For_Pdf:
    class: 'Presta_Shop\Module\Psgdpr\Service\Front_Responder\Strategy\Front_Responder_For_Pdf'
    tags: ["psgdpr.frontResponder"]
    arguments:
      - '@Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Export_Service'

  Presta_Shop\Module\Psgdpr\Repository\Consent_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Consent_Repository'
    public: true
    arguments:
      - "@Doctrine\\Persistence\\ManagerRegistry"
