services:
  _defaults:
    public: false

  Presta_Shop\Module\Psgdpr\Controller\Admin\Customer_Controller:
    class: 'Presta_Shop\Module\Psgdpr\Controller\Admin\Customer_Controller'
    public: true
    arguments:
      - "@prestashop.core.query_bus"
      - '@Presta_Shop\Module\Psgdpr\Repository\Order_Invoice_Repository'
      - '@Presta_Shop\Module\Psgdpr\Service\Back_Responder\Back_Responder_Factory'

  Presta_Shop\Module\Psgdpr\Controller\Admin\Download_Customer_Invoices_Controller:
    class: 'Presta_Shop\Module\Psgdpr\Controller\Admin\Download_Customer_Invoices_Controller'
    public: true
    arguments:
      - '@Presta_Shop\Module\Psgdpr\Repository\Order_Invoice_Repository'
