services:
  _defaults:
    public: false

  Presta_Shop\Module\Psgdpr\Repository\Logger_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Logger_Repository'
    public: true
    arguments:
      - "@Doctrine\\Persistence\\ManagerRegistry"

  Presta_Shop\Module\Psgdpr\Repository\Cart_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Cart_Repository'
    arguments:
      - "@doctrine.dbal.default_connection"

  Presta_Shop\Module\Psgdpr\Repository\Cart_Rule_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Cart_Rule_Repository'
    arguments:
      - "@doctrine.dbal.default_connection"

  Presta_Shop\Module\Psgdpr\Repository\Customer_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Customer_Repository'
    arguments:
      - "@doctrine.dbal.default_connection"

  Presta_Shop\Module\Psgdpr\Repository\Order_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Order_Repository'
    arguments:
      - "@doctrine.dbal.default_connection"

  Presta_Shop\Module\Psgdpr\Repository\Order_Invoice_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Order_Invoice_Repository'
    arguments:
      - "@doctrine.dbal.default_connection"

  Presta_Shop\Module\Psgdpr\Repository\Consent_Repository:
    class: 'Presta_Shop\Module\Psgdpr\Repository\Consent_Repository'
    public: true
    arguments:
      - "@Doctrine\\Persistence\\ManagerRegistry"
