imports:
  - { resource: ./controllers.yml }
  - { resource: ./repositories.yml }

services:
  _defaults:
    public: false

  Psgdpr:
    class: "Psgdpr"
    factory: ["Module", "getInstanceByName"]
    arguments:
      - "psgdpr"

  Presta_Shop\Module\Psgdpr\Service\Logger_Service:
    class: 'Presta_Shop\Module\Psgdpr\Service\Logger_Service'
    arguments:
      - "@PrestaShop\\Module\\Psgdpr\\Repository\\LoggerRepository"
      - "@PrestaShop\\Module\\Psgdpr\\Repository\\CustomerRepository"

  Presta_Shop\Module\Psgdpr\Service\Export_Service:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export_Service'
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@=service("Psgdpr").getTranslator()'

  Presta_Shop\Module\Psgdpr\Service\Customer_Service:
    class: 'Presta_Shop\Module\Psgdpr\Service\Customer_Service'
    arguments:
      - "@Psgdpr"
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@Presta_Shop\Module\Psgdpr\Repository\Cart_Repository'
      - '@Presta_Shop\Module\Psgdpr\Repository\Cart_Rule_Repository'
      - '@Presta_Shop\Module\Psgdpr\Repository\Customer_Repository'
      - "@prestashop.core.command_bus"
      - "@prestashop.core.query_bus"
      - "@prestashop.adapter.group.provider.default_groups_provider"
      - "@hashing"

  Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Csv:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Csv'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'

  Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Pdf:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Pdf'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'

  Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Json:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Strategy\Export_To_Json'
    tags: ["psgdpr.export.customerData"]
    arguments:
      - '@=service("prestashop.adapter.legacy.context").getContext()'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'

  Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory:
    class: 'Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory'
    arguments:
      - !tagged_iterator psgdpr.export.customerData

  Presta_Shop\Module\Psgdpr\Service\Back_Responder\Strategy\Back_Responder_By_Customer_Id:
    class: 'Presta_Shop\Module\Psgdpr\Service\Back_Responder\Strategy\Back_Responder_By_Customer_Id'
    tags: ["psgdpr.export.backResponder"]
    arguments:
      - '@Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory'
      - '@Presta_Shop\Module\Psgdpr\Repository\Customer_Repository'
      - '@Presta_Shop\Module\Psgdpr\Service\Customer_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Export_Service'

  Presta_Shop\Module\Psgdpr\Service\Back_Responder\Strategy\Back_Responder_By_Email:
    class: 'Presta_Shop\Module\Psgdpr\Service\Back_Responder\Strategy\Back_Responder_By_Email'
    tags: ["psgdpr.export.backResponder"]
    arguments:
      - '@Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory'
      - '@Presta_Shop\Module\Psgdpr\Repository\Customer_Repository'
      - '@Presta_Shop\Module\Psgdpr\Service\Customer_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Export_Service'

  Presta_Shop\Module\Psgdpr\Service\Back_Responder\Strategy\Back_Responder_By_Phone:
    class: 'Presta_Shop\Module\Psgdpr\Service\Back_Responder\Strategy\Back_Responder_By_Phone'
    tags: ["psgdpr.export.backResponder"]
    arguments:
      - '@Presta_Shop\Module\Psgdpr\Service\Export\Export_Factory'
      - '@Presta_Shop\Module\Psgdpr\Repository\Customer_Repository'
      - '@Presta_Shop\Module\Psgdpr\Service\Customer_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Logger_Service'
      - '@Presta_Shop\Module\Psgdpr\Service\Export_Service'

  Presta_Shop\Module\Psgdpr\Service\Back_Responder\Back_Responder_Factory:
    class: 'Presta_Shop\Module\Psgdpr\Service\Back_Responder\Back_Responder_Factory'
    arguments:
      - !tagged_iterator psgdpr.export.backResponder
